### ISSUE TITLE
Skip payments not generated by this plugin. 

### ISSUE THREAD

**Issue by mintplugins** [restrictcontentpro/rcp-edd-member-downloads#10]
When a customer downloads an item, it first checks to see if they have an existing payment for this item and uses that payment instead of generating a new one. 

However, if, before this plugin was installed, a payment exists for that item, it should not be used. 

This situation was discovered by a customer who's customers were not getting their expected downloads for only specific products. This is because the customer had a previously existing payment where both the file-being-downloaded and another file were purchased in the same payment. 

Proposal: 
When creating a new payment, add a peice of payment meta letting the payment know it was created by this plugin. Upon subsequent downloads, if the payment does not contain that peice of post meta, skip that payment and generate a new one instead. 

Customer Ticket:
https://secure.helpscout.net/conversation/303899872/50779/?folderId=749231

Line in question:
https://github.com/restrictcontentpro/rcp-edd-member-downloads/blob/master/rcp-edd-member-downloads.php#L273

**Comment by pippinsplugins** [comment]
@mindctrl we could add a piece of meta data to identify the payments for this plugin.

**Comment by mindctrl** [comment]
Meta data makes sense. It would create an issue in the short term for people who've downloaded files in their current period, because if they download them again it will count twice towards their limit, but I think in the long term that's the best way to go.

**Comment by mindctrl** [comment]
The PR works if you haven't purchased the item before, but if you have the Download button does nothing because the file URL is empty.

As a backup, I think we need to do a query without the meta value and loop through the cart details array to check for a download ID match.

**Comment by mindctrl** [comment]
I couldn't push to @mintplugins repo to add to the PR, despite Github telling me I could. I went ahead and merged the PR and added to it. The fallback is here: https://github.com/restrictcontentpro/rcp-edd-member-downloads/commit/1a13613e9309c5aa8b95c9637c175275111819bf

**Comment by mindctrl** [comment]
@pippinsplugins can you double check my work there before I close this?

**Comment by pippinsplugins** [comment]
Looks good to me.
