### ISSUE TITLE
daily restriction

### ISSUE THREAD

**Issue by taymaz1990** [restrictcontentpro/rcp-edd-member-downloads#22]
hey there this is so cool but there is an issue to be discussed here and if any one could help i would appreciate that.
i want to use download restrictions daily for any member that has lets say an account for one month but he or she should not download for example more than 10 files per day.

**Comment by mindctrl** [comment]
Hi @taymaz1990,

We use Github for development tracking only. Please open a support ticket for any pre-sales and support questions. https://restrictcontentpro.com/support/
