### ISSUE TITLE
Add spinner to download button after it's been clicked

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-edd-member-downloads#27]
When you add a normal product to your cart in EDD, you click the add to cart button and then the text is replaced with a spinner as it waits for that process to happen. It would be nice if we could use this spinner when you click on the Download button in this add-on, as it waits for the ajax request.

We had one customer bring this up because the process of adding a new EDD payment, etc. was taking a long time and it wasn't clear to the end user that anything was actually happening.

**Comment by nosegraze** [comment]
PR: #31

**Comment by misulicus** [comment]
It works but i find the placement of the image a bit weird : https://www.screencast.com/t/pfDesaNN

**Comment by nosegraze** [comment]
@misulicus Which theme are you using? It doesn't look like that for me so I'll give it a test in that theme. Does the normal EDD add to cart button look like that too?

**Comment by misulicus** [comment]
that was on 2017
This is on 2019 as soon as you hit the Download button: https://www.screencast.com/t/JTS1vXntHObD

Normall Edd add to cart 2019 theme: https://www.screencast.com/t/3ZfvJShTwv

**Comment by nosegraze** [comment]
Hm I tested in 2017 and experienced a slightly different result from your screenshot. I did push up a tweak though -- can you see if this fixes it for you now too?

**Comment by misulicus** [comment]
Yeah much better, in the middle of the button just like normal EDD.
