### ISSUE TITLE
RCP 3.1 integration - multiple memberships

### ISSUE THREAD

**Issue by nosegraze** [restrictcontentpro/rcp-edd-member-downloads#33]
How will this work with multiple memberships? What if they're on a membership with an allowance of 3 per month, then they're also on a membership with an allowance of 20 per year? What is their actual allowance?

**Comment by pippinsplugins** [comment]
A simple solution would be to use whichever number is higher. Typically a higher download limit would be tied to a more expensive membership, so giving the higher allowance would make sense.

**Comment by nosegraze** [comment]
What if the durations are different? Example:

Membership A: 5 downloads per month
Membership B: 50 downloads per year

Membership B is a higher number, but technically a lower allowance (4.1 downloads per month).

So we could just literally take the higher number, or do some "per day" calculations to figure out which one actually offers more downloads over an equal amount of time.

**Comment by misulicus** [comment]
Can’t we make it only work by default and allow filtering to increase and force it to be x downloads/month ?
So even if they have 2 memberships one monthly recurring and one yearly the download limits will always be x/month

In this case the store owner will have to do the math and set a download/month number

**Comment by nosegraze** [comment]
Forcing it to be per month would be a pretty big overhaul from our current implementation and might potentially disrupt a lot of existing sites. For example, forcing it to be per month might not be a big deal for a yearly membership, but it might make things really odd for a daily / weekly membership. Example:

- Say someone offers 5 downloads per day for a daily membership.
- This is the equivalent of, let's say 150 per month.
- So suddenly we would change 5/day to 150/month. This potentially means someone can now download 150 on one single day and then not renew the following day. This is way more than originally intended with 5/day. It would only work if the person intended on paying for the daily membership for a whole 30 days.

**Comment by nosegraze** [comment]
PR: #36

**Comment by nosegraze** [comment]
Don't test this yet. I think I need to rework it a bit.

**Comment by nosegraze** [comment]
Updated PR. @misulicus This is ready for initial testing. For now, let's test with:

- EDD Member Downloads `issue/33` branch.
- Restrict Content Pro `master` branch.
- Group Accounts `master` branch.

## Initial Testing

- [ ] Put `[rcp_edd_member_downloads_remaining]` shortcode on a page. It should be `0` while viewing with no membership.
- [ ] Configure a membership level with a download allowance of `10` per month and group account features and sign up for this level. `[rcp_edd_member_downloads_remaining]` shortcode should update to show full allowance (`10`).
- [ ] Download an EDD product for free. `[rcp_edd_member_downloads_remaining]` should show one less remaining than before (`9`).
- [ ] Refund the EDD payment from the previous step. `[rcp_edd_member_downloads_remaining]` should go back up to full allowance (`10`).
- [ ] Download a different EDD product for free. `[rcp_edd_member_downloads_remaining]` should show one less remaining than before (`9`).
- [ ] Invite someone to join your group and accept the invite. Then log in as this group member.
- [ ] The group member should have the full allowance when viewing the `[rcp_edd_member_downloads_remaining]` shortcode (`10`).
- [ ] Group member download an EDD product. `[rcp_edd_member_downloads_remaining]` should now be `9` for the group member. However, check the group owner and make sure their allowance number is also still `9`. It should not be `8` because the owner and member have separate counts.
- [ ] Log in to the admin panel and edit this membership (Restrict > Memberships). Use the form to add a new payment _and renew_.
- [ ] The group owner should have their allowance set back to `10`.
- [ ] The group member should also have their allowance set back to `10`.

---

Once we confirm this is all still working with RCP `master` we'll start testing with multiple memberships.

**Comment by misulicus** [comment]
@nosegraze all good here !

**Comment by nosegraze** [comment]
- EDD Member Downloads `issue/33` branch.
- Restrict Content Pro `release/3.1` branch.
- Group Accounts `master` branch.

## Multiple Memberships Testing

- [ ] Enable multiple memberships in Restrict > Settings > General.
- [ ] Configure a membership level (Level A) with a download allowance of `10` per month.
- [ ] Configure a second membership level (Level B) with a download allowance of `20` per month.
- [ ] Sign up for Level A. `[rcp_edd_member_downloads_remaining]` should output `10`.
- [ ] Sign up for Level B as a second membership. `[rcp_edd_member_downloads_remaining]` should output `20`. This is because it sees 20 as the higher allowance from Level B. The allowances do not combine.
- [ ] Download an EDD product for free. `[rcp_edd_member_downloads_remaining]` should show one less remaining than before (`19`).
