### ISSUE TITLE
Add option to enable/disable and set unlimited

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-edd-member-downloads#4]
Right now the feature is disabled on a level by setting the value to `0`. It might make more sense to introduce a checkbox to enable/disable and use `0` to allow unlimited downloads. Right now doing "unlimited" means setting a very high number. Thoughts @pippinsplugins

**Comment by pippinsplugins** [comment]
I like the idea of a checkbox. That way it's not left up to the user to figure it out.

**Comment by nosegraze** [comment]
In the Job Manager add-on we just use a very high number. I'm fine going either way but maybe we should keep them the same whichever way we go to maintain some consistency.

**Comment by mindctrl** [comment]
Yeah I think at this point I'd prefer to leave it as is to avoid introducing any bugs or unexpected behavior.
