### ISSUE TITLE
Add ability to show downloads remaining

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-edd-member-downloads#5]
Customer asked about ability to show the number of downloads remaining to a member. I think this is a good idea. Maybe we can introduce a shortcode for this.

**Comment by nosegraze** [comment]
PR: #9 

Not sure if we wanted to do anything fancy with adding text to the shortcode or whatevs, so it's literally just a number.

**Comment by mindctrl** [comment]
Works good! I like the minimal number only output. It lets people easily do whatever they want. Merged.
