### ISSUE TITLE
Credit downloads remaining when refunded?

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-edd-member-downloads#6]
Customer asked if there was a way to credit a member back if they're unhappy with a download. We could look at doing this when the purchase record is refunded. Thoughts @pippinsplugins?

**Comment by pippinsplugins** [comment]
Should be pretty easy to do. Just decrement the counter when the 0.00 payment record is marked as refunded.

**Comment by nosegraze** [comment]
PR: #13
