### ISSUE TITLE
Improve the javascript target for the ajax request

### ISSUE THREAD

**Issue by mindctrl** [restrictcontentpro/rcp-edd-member-downloads#7]
Came across a theme today that displays the button 3 times on a single page, 2 of which were hidden with CSS. The buttons were loading next to an audio player. No idea why.

This caused an issue where the ajax request fired 3 times. Some other pages on his site appeared to have more than 3 buttons for the same product. Yeah. This was causing slow download times due to numerous ajax requests firing off at the same time. To prevent this, we need to refine the javascript targeting.

**Comment by pippinsplugins** [comment]
We could set a "processing" var to true when it starts and bail early if already true, indicating it was started somewhere else. We do this in core for registration processing.

**Comment by mindctrl** [comment]
PR submitted. Ready for testing. @michaelbeil mind giving this a quick test since you saw it in action? I tested with Marketify and Twenty Twelve, both work fine for me locally.

**Comment by pippinsplugins** [comment]
Looks great to me. Merged.
